---
- name: Installs python before fact gathering occurs
  hosts: all

  become: yes
  gather_facts: False

  pre_tasks:
    - raw: test -e /usr/bin/python || (apt install -y python-minimal)
    - raw: test -e /usr/bin/pip || (apt install -y python-pip)
    - setup: # aka gather_facts
