---
# - name: ensure locales is installed
#   package: name=locales state=latest

# - name: detect locale configuration file
#   stat: path={{ locale_config_path }}
#   register: locale_configuration

# - name: ensure locale configuration file is created
#   file: path={{ locale_config_path }} state=touch
#   when: not locale_configuration.stat.exists

# - name: generate locales
#   command: locale-gen {{ item.locale }}
#   with_items: locale_locales

- name: ensure the system locale is configured
  command: localectl set-locale {{ item.category }}={{ item.locale }}
  with_items: "{{ locale_categories }}"
  tags: locale
